### ISSUE TITLE
Some tezos fxhash items can't be updated with the latest metadata

### ISSUE THREAD

**Issue by lulurel** [gallery-so/gallery#1180]
These items show "waiting to be signed", despite fxhash already signing them and the items being correctly displayed on fxhash.xyz and objkt.com.

For example, https://gallery.so/lulu/2INm7jRqF0XEKz4g5ABAL0cbJ4O/2INm4jriRoByxSssd5HgD801EO6

**Comment by lulurel** [comment]
Looks like the issue has been fixed.

**Comment by Robinnnnn** [comment]
Thanks for the report @lulurel 🙏
