### ISSUE TITLE
Investigate Web3 Native Auth

### ISSUE THREAD

**Issue by Robinnnnn** [gallery-so/gallery#2]
What's the best way to do web3 logins?

https://walletconnect.org

https://github.com/3box/3box

**Comment by mikeydub** [comment]
some examples of web3 sign in flows:

- https://foundation.app
- https://pooltogether.com
- https://app.uniswap.org/
- https://flamingodao.xyz
- https://tryshowtime.com

all pretty uniform:

- sign in with wallet button
- popover with metamask, wallet connect, or other
- initiates sign with wallet
- then you're signed in

**Comment by mikeydub** [comment]
came across this library / example if we want to use

https://github.com/Web3Modal/web3modal
